<a href="https://colab.research.google.com/github/K-K-0/MLP-Assignments/blob/main/Week_9_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [233]:
import numpy as np
import pandas as pd

In [234]:
Url= "https://archive.ics.uci.edu/ml/machine-learning-databases/00488/Live_20210128.csv"
df = pd.read_csv(Url)

In [235]:
df.head()

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,Column1,Column2,Column3,Column4
0,1,video,4/22/2018 6:00,529,512,262,432,92,3,1,1,0,NaN,NaN,NaN,NaN
1,2,photo,4/21/2018 22:45,150,0,0,150,0,0,0,0,0,NaN,NaN,NaN,NaN
2,3,video,4/21/2018 6:17,227,236,57,204,21,1,1,0,0,NaN,NaN,NaN,NaN
3,4,photo,4/21/2018 2:29,111,0,0,111,0,0,0,0,0,NaN,NaN,NaN,NaN
4,5,photo,4/18/2018 3:22,213,0,0,204,9,0,0,0,0,NaN,NaN,NaN,NaN

In [236]:
df.shape

(7050, 16)

In [237]:
df['status_type'].unique()

array(['video', 'photo', 'link', 'status'], dtype=object)

In [238]:
df.isna().sum()

status_id              0
status_type            0
status_published       0
num_reactions          0
num_comments           0
num_shares             0
num_likes              0
num_loves              0
num_wows               0
num_hahas              0
num_sads               0
num_angrys             0
Column1             7050
Column2             7050
Column3             7050
Column4             7050
dtype: int64

In [239]:
df = df.dropna(axis=1)

In [240]:
df.isna().sum()

status_id           0
status_type         0
status_published    0
num_reactions       0
num_comments        0
num_shares          0
num_likes           0
num_loves           0
num_wows            0
num_hahas           0
num_sads            0
num_angrys          0
dtype: int64

In [241]:
df.head()

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys
0,1,video,4/22/2018 6:00,529,512,262,432,92,3,1,1,0
1,2,photo,4/21/2018 22:45,150,0,0,150,0,0,0,0,0
2,3,video,4/21/2018 6:17,227,236,57,204,21,1,1,0,0
3,4,photo,4/21/2018 2:29,111,0,0,111,0,0,0,0,0
4,5,photo,4/18/2018 3:22,213,0,0,204,9,0,0,0,0

In [242]:
X = df.drop(columns=['status_id', 'status_type', 'status_published'], axis=1)
y = df['status_type']

In [243]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

lr = LabelEncoder()
y = lr.fit_transform(y)

In [244]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,random_state=42
)

In [245]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [246]:
from sklearn.cluster import KMeans

model = KMeans(n_clusters=4,random_state=10)

model.fit(X_train,y_train)
model.inertia_

25918.57619293958

In [247]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, model.predict(X_test))

array([[  6,   0,   0,   5],
       [838,   5,   0,  40],
       [ 47,   0,   0,  17],
       [371,  58,   6,  17]])

In [248]:
from sklearn.cluster import AgglomerativeClustering

model1 = AgglomerativeClustering(
    n_clusters=4,
    linkage='ward'
)
model1.fit(X_train, y_train)
accuracy_score(y_test, model1.fit_predict(X_test))

0.6042553191489362

In [249]:
len(X_train)

5640